In [2]:
import pandas as pd
import numpy as np
import json

In [3]:
data = []

with open("../data/candidates.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        data.append(json.loads(line))

print(data[:2])

[{'candidate_id': 'CAND_0000001', 'profile': {'anonymized_name': 'Ira Vora', 'headline': 'Backend Engineer | SQL, Spark, Cloud', 'summary': "Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.", 'location': 'Toronto', 'country': 'Canada', 'years_of_experience': 6.9, 'current_title': 'Backend Engineer', 'current_company': 'Mindtree', 'current_company_size': '10001+', 'current_industry': 'IT Services'}, 'career_history': [{'company': 'Mindtree', 'title': 'Backend Engineer', 'start_date': '2024-03-08', 'end_date': None, 'duration_months': 27, 'is_current': True, 'industry': 'IT Services', 'company_size': '10001+', 'description': 'Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure.'}, {'company': 'Dunder Mifflin', 'title': 'Analytics Engineer', 'start_date': '2019-07-03', 'end_date': '2024-01-08', 'duration_months': 55, 'is_current': False, 'industry': 'Paper Products', 'company_size': '201-500', 'description': 'Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models.'}], 'education': [{'institution': 'Lovely Professional University', 'degree': 'B.E.', 'field_of_study': 'Computer Science', 'start_year': 2017, 'end_year': 2020, 'grade': '8.24 CGPA', 'tier': 'tier_3'}], 'skills': [{'name': 'Tailwind', 'proficiency': 'intermediate', 'endorsements': 3, 'duration_months': 13}, {'name': 'NLP', 'proficiency': 'advanced', 'endorsements': 37, 'duration_months': 26}, {'name': 'Image Classification', 'proficiency': 'advanced', 'endorsements': 7, 'duration_months': 40}, {'name': 'Fine-tuning LLMs', 'proficiency': 'advanced', 'endorsements': 21, 'duration_months': 36}, {'name': 'Weights & Biases', 'proficiency': 'intermediate', 'endorsements': 13, 'duration_months': 30}, {'name': 'Speech Recognition', 'proficiency': 'advanced', 'endorsements': 52, 'duration_months': 33}, {'name': 'Photoshop', 'proficiency': 'intermediate', 'endorsements': 8, 'duration_months': 24}, {'name': 'TTS', 'proficiency': 'advanced', 'endorsements': 56, 'duration_months': 60}, {'name': 'LoRA', 'proficiency': 'intermediate', 'endorsements': 0, 'duration_months': 28}, {'name': 'Apache Beam', 'proficiency': 'intermediate', 'endorsements': 4, 'duration_months': 9}, {'name': 'AWS', 'proficiency': 'beginner', 'endorsements': 5, 'duration_months': 8}, {'name': 'Flask', 'proficiency': 'beginner', 'endorsements': 15, 'duration_months': 15}, {'name': 'BentoML', 'proficiency': 'intermediate', 'endorsements': 3, 'duration_months': 36}, {'name': 'Milvus', 'proficiency': 'advanced', 'endorsements': 40, 'duration_months': 35}, {'name': 'GANs', 'proficiency': 'advanced', 'endorsements': 12, 'duration_months': 19}, {'name': 'Statistical Modeling', 'proficiency': 'intermediate', 'endorsements': 9, 'duration_months': 8}, {'name': 'GCP', 'proficiency': 'beginner', 'endorsements': 7, 'duration_months': 2}], 'certifications': [], 'languages': [{'language': 'English', 'proficiency': 'professional'}, {'language': 'Hindi', 'proficiency': 'conversational'}], 'redrob_signals': {'profile_completeness_score': 86.9, 'signup_date': '2025-10-16', 'last_active_date': '2026-05-20', 'open_to_work_flag': True, 'profile_views_received_30d': 23, 'applications_submitted_30d': 2, 'recruiter_response_rate': 0.34, 'avg_response_time_hours': 177.8, 'skill_assessment_scores': {'NLP': 38.8, 'Image Classification': 64.8, 'Fine-tuning LLMs': 41.6, 'Speech Recognition': 53.7}, 'connection_count': 356, 'endorsements_received': 35, 'notice_period_days': 60, 'expected_salary_range_inr_lpa': {'min': 18.7, 'max': 36.1}, 'preferred_work_mode': 'onsite', 'willing_to_relocate': False, 'github_activity_score': 9.2, 'search_appearance_30d': 249, 'saved_by_recruiters_30d': 4, 'interview_completion_rate': 0.71, 'offer_acceptance_rate': 0.58, 'verified_email': True, 'verified_phone': True, 'linkedin_connected': False}}, {'candidate_id': 'CAND_0000002', 'profile': {'anonymized_name': 'Saanvi Sethi', 'headline': 'Operations Manager | 12.5+ yrs experience', 'summary': "Professional with 12.5+ years of experience. My professional background is in marketing manager — I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.", 'location': 'Chennai, Tamil Nadu', 'country': 'India', 'years_of_experience': 12.5, 'current_title': 'Operations Manager', 'current_company': 'Wipro', 'current_company_size': '10001+', 'current_industry': 'IT Services'}, 'career_history': [{'company': 'Wipro', 'title': 'Operations Manager', 'start_date': '2022-11-14', 'end_date': None, 'duration_months': 43, 'is_current': True, 'industry': 'IT Services', 'company_size': '10001+', 'description': 'Customer support team lead at a SaaS product. Managed a team of 8 support agents handling tier-1 and tier-2 tickets; owned the escalation process to engineering and the customer-feedback loop to product. Built out the support knowledge base and the agent training program. Strong on the people-management side and the process side; lighter on technical depth beyond product expertise.'}, {'company': 'Wipro', 'title': 'Operations Manager', 'start_date': '2021-09-13', 'end_date': '2022-11-07', 'duration_months': 14, 'is_current': False, 'industry': 'IT Services', 'company_size': '10001+', 'description': 'Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked closely with manufacturing partners on production scale-up.'}, {'company': 'Acme Corp', 'title': 'Marketing Manager', 'start_date': '2017-03-08', 'end_date': '2021-08-14', 'duration_months': 54, 'is_current': False, 'industry': 'Manufacturing', 'company_size': '201-500', 'description': 'Content writing and SEO strategy for a tech-focused publication. Wrote longform articles on developer tools, cloud platforms, and AI/ML topics — including some that ranked on the first page of search for high-competition keywords. Managed a freelance writer pool and the editorial calendar. Recent work has been on AI-assisted content production, using LLM tools for research, drafting, and editing while maintaining editorial quality.'}, {'company': 'Dunder Mifflin', 'title': 'Marketing Manager', 'start_date': '2014-01-23', 'end_date': '2017-03-08', 'duration_months': 38, 'is_current': False, 'industry': 'Paper Products', 'company_size': '201-500', 'description': 'Brand design and creative direction at a consumer-products company. Owned brand identity (logo, visual system, typography), packaging design, and digital creative across web and social. Led the recent rebrand and managed a small external agency for production work. Comfortable across the Adobe suite, Figma, and the production side of brand and packaging design.'}], 'education': [{'institution': 'Local Engineering College', 'degree': 'B.Sc', 'field_of_study': 'Mathematics', 'start_year': 2007, 'end_year': 2011, 'grade': '77%', 'tier': 'tier_4'}], 'skills': [{'name': 'Project Management', 'proficiency': 'intermediate', 'endorsements': 14, 'duration_months': 23}, {'name': 'React', 'proficiency': 'intermediate', 'endorsements': 6, 'duration_months': 35}, {'name': 'Photoshop', 'proficiency': 'intermediate', 'endorsements': 9, 'duration_months': 35}, {'name': 'TypeScript', 'proficiency': 'beginner', 'endorsements': 2, 'duration_months': 3}, {'name': 'Marketing', 'proficiency': 'beginner', 'endorsements': 9, 'duration_months': 11}, {'name': 'Kafka', 'proficiency': 'intermediate', 'endorsements': 3, 'duration_months': 16}, {'name': 'JavaScript', 'proficiency': 'beginner', 'endorsements': 9, 'duration_months': 3}, {'name': 'Feature Engineering', 'proficiency': 'intermediate', 'endorsements': 11, 'duration_months': 27}, {'name': 'GCP', 'proficiency': 'intermediate', 'endorsements': 7, 'duration_months': 30}], 'certifications': [], 'languages': [{'language': 'English', 'proficiency': 'professional'}, {'language': 'Hindi', 'proficiency': 'conversational'}], 'redrob_signals': {'profile_completeness_score': 78.7, 'signup_date': '2025-07-28', 'last_active_date': '2025-11-12', 'open_to_work_flag': True, 'profile_views_received_30d': 7, 'applications_submitted_30d': 1, 'recruiter_response_rate': 0.29, 'avg_response_time_hours': 171.6, 'skill_assessment_scores': {}, 'connection_count': 179, 'endorsements_received': 3, 'notice_period_days': 60, 'expected_salary_range_inr_lpa': {'min': 8.8, 'max': 9.0}, 'preferred_work_mode': 'flexible', 'willing_to_relocate': False, 'github_activity_score': -1, 'search_appearance_30d': 107, 'saved_by_recruiters_30d': 10, 'interview_completion_rate': 0.62, 'offer_acceptance_rate': -1, 'verified_email': False, 'verified_phone': False, 'linkedin_connected': False}}]

In [4]:
data[0].keys()

dict_keys(['candidate_id', 'profile', 'career_history', 'education', 'skills', 'certifications', 'languages', 'redrob_signals'])

In [5]:
cols = ['candidate_id', 'profile', 'career_history', 'education', 'skills', 'certifications', 'languages', 'redrob_signals']
df = pd.DataFrame(columns=cols)
df.columns

Index(['candidate_id', 'profile', 'career_history', 'education', 'skills',
       'certifications', 'languages', 'redrob_signals'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   candidate_id    0 non-null      object
 1   profile         0 non-null      object
 2   career_history  0 non-null      object
 3   education       0 non-null      object
 4   skills          0 non-null      object
 5   certifications  0 non-null      object
 6   languages       0 non-null      object
 7   redrob_signals  0 non-null      object
dtypes: object(8)
memory usage: 132.0+ bytes

In [7]:
df = pd.DataFrame(data)

In [8]:
df

,candidate_id,profile,career_history,education,skills,certifications,languages,redrob_signals
0,CAND_0000001,"{'anonymized_name': 'Ira Vora', 'headline': 'B...","[{'company': 'Mindtree', 'title': 'Backend Eng...",[{'institution': 'Lovely Professional Universi...,"[{'name': 'Tailwind', 'proficiency': 'intermed...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 86.9, 'signup_d..."
1,CAND_0000002,"{'anonymized_name': 'Saanvi Sethi', 'headline'...","[{'company': 'Wipro', 'title': 'Operations Man...","[{'institution': 'Local Engineering College', ...","[{'name': 'Project Management', 'proficiency':...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 78.7, 'signup_d..."
2,CAND_0000003,"{'anonymized_name': 'Yash Agarwal', 'headline'...","[{'company': 'TCS', 'title': 'Customer Support...","[{'institution': 'Local Engineering College', ...","[{'name': 'Angular', 'proficiency': 'intermedi...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 31.9, 'signup_d..."
3,CAND_0000004,"{'anonymized_name': 'Anil Bose', 'headline': '...","[{'company': 'Dunder Mifflin', 'title': 'Marke...","[{'institution': 'Local Engineering College', ...","[{'name': 'Node.js', 'proficiency': 'intermedi...","[{'name': 'AWS Certified Cloud Practitioner', ...","[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 28.5, 'signup_d..."
4,CAND_0000005,"{'anonymized_name': 'Aisha Sethi', 'headline':...","[{'company': 'Stark Industries', 'title': 'Acc...","[{'institution': 'Chandigarh University', 'deg...","[{'name': 'SQL', 'proficiency': 'beginner', 'e...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 84.6, 'signup_d..."
...,...,...,...,...,...,...,...,...
99995,CAND_0099996,"{'anonymized_name': 'Myra Sethi', 'headline': ...","[{'company': 'Wipro', 'title': 'Operations Man...","[{'institution': 'KIIT University', 'degree': ...","[{'name': 'Content Writing', 'proficiency': 'b...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 41.4, 'signup_d..."
99996,CAND_0099997,"{'anonymized_name': 'Priya Krishnan', 'headlin...","[{'company': 'Hooli', 'title': 'Mechanical Eng...","[{'institution': 'SRM Chennai', 'degree': 'Ph....","[{'name': 'MongoDB', 'proficiency': 'beginner'...",[],"[{'language': 'English', 'proficiency': 'nativ...","{'profile_completeness_score': 42.7, 'signup_d..."
99997,CAND_0099998,"{'anonymized_name': 'Shreya Agarwal', 'headlin...","[{'company': 'InMobi', 'title': 'Analytics Eng...",[{'institution': 'Manipal Institute of Technol...,"[{'name': 'Feature Engineering', 'proficiency'...","[{'name': 'AWS Certified Cloud Practitioner', ...","[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 75.9, 'signup_d..."
99998,CAND_0099999,"{'anonymized_name': 'Diya Menon', 'headline': ...","[{'company': 'HCL', 'title': '.NET Developer',...","[{'institution': 'RV College of Engineering', ...","[{'name': 'SEO', 'proficiency': 'intermediate'...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 49.1, 'signup_d..."
99999,CAND_0100000,"{'anonymized_name': 'Reyansh Reddy', 'headline...","[{'company': 'Acme Corp', 'title': 'Mechanical...","[{'institution': 'Chandigarh University', 'deg...","[{'name': 'GCP', 'proficiency': 'intermediate'...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 80.1, 'signup_d..."

In [9]:
df.columns

Index(['candidate_id', 'profile', 'career_history', 'education', 'skills',
       'certifications', 'languages', 'redrob_signals'],
      dtype='str')

In [10]:
for col in df.columns:
    print(col)
    print(type(df[col].iloc[0]))

candidate_id
<class 'str'>
profile
<class 'dict'>
career_history
<class 'list'>
education
<class 'list'>
skills
<class 'list'>
certifications
<class 'list'>
languages
<class 'list'>
redrob_signals
<class 'dict'>

In [11]:
# candidate_id
# <class 'str'>
# profile
# <class 'dict'>
# career_history
# <class 'list'>
# education
# <class 'list'>
# skills
# <class 'list'>
# certifications
# <class 'list'>
# languages
# <class 'list'>
# redrob_signals
# <class 'dict'>

In [12]:
for col in df.columns:
    print(df[col].head())

0    CAND_0000001
1    CAND_0000002
2    CAND_0000003
3    CAND_0000004
4    CAND_0000005
Name: candidate_id, dtype: str
0    {'anonymized_name': 'Ira Vora', 'headline': 'B...
1    {'anonymized_name': 'Saanvi Sethi', 'headline'...
2    {'anonymized_name': 'Yash Agarwal', 'headline'...
3    {'anonymized_name': 'Anil Bose', 'headline': '...
4    {'anonymized_name': 'Aisha Sethi', 'headline':...
Name: profile, dtype: object
0    [{'company': 'Mindtree', 'title': 'Backend Eng...
1    [{'company': 'Wipro', 'title': 'Operations Man...
2    [{'company': 'TCS', 'title': 'Customer Support...
3    [{'company': 'Dunder Mifflin', 'title': 'Marke...
4    [{'company': 'Stark Industries', 'title': 'Acc...
Name: career_history, dtype: object
0    [{'institution': 'Lovely Professional Universi...
1    [{'institution': 'Local Engineering College', ...
2    [{'institution': 'Local Engineering College', ...
3    [{'institution': 'Local Engineering College', ...
4    [{'institution': 'Chandigarh University', 'deg...
Name: education, dtype: object
0    [{'name': 'Tailwind', 'proficiency': 'intermed...
1    [{'name': 'Project Management', 'proficiency':...
2    [{'name': 'Angular', 'proficiency': 'intermedi...
3    [{'name': 'Node.js', 'proficiency': 'intermedi...
4    [{'name': 'SQL', 'proficiency': 'beginner', 'e...
Name: skills, dtype: object
0                                                   []
1                                                   []
2                                                   []
3    [{'name': 'AWS Certified Cloud Practitioner', ...
4                                                   []
Name: certifications, dtype: object
0    [{'language': 'English', 'proficiency': 'profe...
1    [{'language': 'English', 'proficiency': 'profe...
2    [{'language': 'English', 'proficiency': 'profe...
3    [{'language': 'English', 'proficiency': 'profe...
4    [{'language': 'English', 'proficiency': 'profe...
Name: languages, dtype: object
0    {'profile_completeness_score': 86.9, 'signup_d...
1    {'profile_completeness_score': 78.7, 'signup_d...
2    {'profile_completeness_score': 31.9, 'signup_d...
3    {'profile_completeness_score': 28.5, 'signup_d...
4    {'profile_completeness_score': 84.6, 'signup_d...
Name: redrob_signals, dtype: object

In [13]:
profile_df = pd.json_normalize(df['profile'])
profile_df = pd.concat(
    [
        df[['candidate_id']].reset_index(drop=True),
        profile_df.reset_index(drop=True)
    ],
    axis=1
)
profile_df

,candidate_id,anonymized_name,headline,summary,location,country,years_of_experience,current_title,current_company,current_company_size,current_industry
0,CAND_0000001,Ira Vora,"Backend Engineer | SQL, Spark, Cloud",Software / data professional with 6.9 years of...,Toronto,Canada,6.9,Backend Engineer,Mindtree,10001+,IT Services
1,CAND_0000002,Saanvi Sethi,Operations Manager | 12.5+ yrs experience,Professional with 12.5+ years of experience. M...,"Chennai, Tamil Nadu",India,12.5,Operations Manager,Wipro,10001+,IT Services
2,CAND_0000003,Yash Agarwal,Customer Support | 1.1+ yrs experience,Professional with 1.1+ years of experience. I'...,Austin,USA,1.1,Customer Support,TCS,10001+,IT Services
3,CAND_0000004,Anil Bose,Marketing Manager | Driving business outcomes,Professional with 3.8+ years of experience. My...,Sydney,Australia,3.8,Marketing Manager,Dunder Mifflin,201-500,Paper Products
4,CAND_0000005,Aisha Sethi,Accountant | Helping teams scale,Professional with 11.0+ years of experience. I...,"Gurgaon, Haryana",India,11.0,Accountant,Stark Industries,1001-5000,Manufacturing
...,...,...,...,...,...,...,...,...,...,...,...
99995,CAND_0099996,Myra Sethi,Operations Manager | 13.4+ yrs experience,Professional with 13.4+ years of experience. I...,"Ahmedabad, Gujarat",India,13.4,Operations Manager,Wipro,10001+,IT Services
99996,CAND_0099997,Priya Krishnan,Mechanical Engineer | 10.6+ yrs experience,Professional with 10.6+ years of experience. I...,"Bangalore, Karnataka",India,10.6,Mechanical Engineer,Hooli,1001-5000,Software
99997,CAND_0099998,Shreya Agarwal,Analytics Engineer | 7.3+ yrs in data engineering,Software / data professional with 7.3 years of...,"Kochi, Kerala",India,7.3,Analytics Engineer,InMobi,1001-5000,AdTech
99998,CAND_0099999,Diya Menon,.NET Developer | Backend systems & APIs,Software engineer with 4.3 years of experience...,"Bhubaneswar, Odisha",India,4.3,.NET Developer,HCL,10001+,IT Services
99999,CAND_0100000,Reyansh Reddy,Mechanical Engineer | 12.4+ yrs experience,Professional with 12.4+ years of experience. I...,"Kolkata, West Bengal",India,12.4,Mechanical Engineer,Acme Corp,201-500,Manufacturing

In [14]:
for col in profile_df.columns:
    print(f"{col} type: {type(profile_df[col].loc[0])}")

candidate_id type: <class 'str'>
anonymized_name type: <class 'str'>
headline type: <class 'str'>
summary type: <class 'str'>
location type: <class 'str'>
country type: <class 'str'>
years_of_experience type: <class 'numpy.float64'>
current_title type: <class 'str'>
current_company type: <class 'str'>
current_company_size type: <class 'str'>
current_industry type: <class 'str'>

In [15]:
redro_df = pd.json_normalize(df['redrob_signals'])
redro_df.sample(20)

,profile_completeness_score,signup_date,last_active_date,open_to_work_flag,profile_views_received_30d,applications_submitted_30d,recruiter_response_rate,avg_response_time_hours,connection_count,endorsements_received,...,skill_assessment_scores.Python,skill_assessment_scores.OpenSearch,skill_assessment_scores.BM25,skill_assessment_scores.scikit-learn,skill_assessment_scores.pgvector,skill_assessment_scores.Embeddings,skill_assessment_scores.LlamaIndex,skill_assessment_scores.PyTorch,skill_assessment_scores.Deep Learning,skill_assessment_scores.QLoRA
25989,59.8,2026-05-13,2026-02-07,False,35,0,0.30,77.9,321,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50965,58.4,2023-04-16,2026-01-25,True,16,10,0.45,48.7,125,21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66995,68.4,2023-12-06,2026-01-25,False,89,7,0.80,64.5,49,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64398,39.6,2025-09-30,2026-02-09,True,30,6,0.45,47.5,468,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72775,73.8,2023-02-18,2026-04-04,True,105,8,0.12,93.7,786,36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69746,37.9,2024-11-09,2025-11-05,False,48,4,0.77,201.1,381,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74784,29.5,2025-05-02,2025-10-15,True,50,2,0.06,222.9,100,32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86283,53.9,2025-10-14,2026-01-01,False,120,5,0.50,121.2,541,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15208,65.1,2026-01-14,2026-04-13,True,77,8,0.23,214.1,536,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36277,29.1,2026-01-17,2025-12-12,False,72,4,0.28,174.6,594,21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65554,63.3,2024-03-05,2026-05-13,False,4,1,0.31,100.5,188,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94316,62.5,2023-08-02,2026-04-19,False,30,5,0.26,79.4,137,68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27302,60.9,2023-01-10,2026-01-03,False,74,10,0.18,116.1,502,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61758,77.2,2025-02-15,2025-12-15,False,30,0,0.69,196.3,142,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87727,75.6,2025-09-27,2026-04-04,False,19,6,0.76,46.2,376,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79504,49.6,2023-10-16,2026-01-11,False,39,10,0.36,278.0,320,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40071,38.3,2024-04-07,2025-10-12,False,7,0,0.12,266.4,304,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48947,41.0,2024-07-12,2026-05-21,False,80,0,0.65,122.1,160,32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4580,81.7,2024-10-22,2025-12-27,False,57,3,0.62,33.5,258,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3727,56.3,2023-08-24,2026-05-15,False,24,8,0.53,154.1,139,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
redro_df.columns

Index(['profile_completeness_score', 'signup_date', 'last_active_date',
       'open_to_work_flag', 'profile_views_received_30d',
       'applications_submitted_30d', 'recruiter_response_rate',
       'avg_response_time_hours', 'connection_count', 'endorsements_received',
       'notice_period_days', 'preferred_work_mode', 'willing_to_relocate',
       'github_activity_score', 'search_appearance_30d',
       'saved_by_recruiters_30d', 'interview_completion_rate',
       'offer_acceptance_rate', 'verified_email', 'verified_phone',
       'linkedin_connected', 'skill_assessment_scores.NLP',
       'skill_assessment_scores.Image Classification',
       'skill_assessment_scores.Fine-tuning LLMs',
       'skill_assessment_scores.Speech Recognition',
       'expected_salary_range_inr_lpa.min',
       'expected_salary_range_inr_lpa.max', 'skill_assessment_scores.GANs',
       'skill_assessment_scores.OpenCV',
       'skill_assessment_scores.Prompt Engineering',
       'skill_assessment_scores.Object Detection',
       'skill_assessment_scores.Recommendation Systems',
       'skill_assessment_scores.FAISS',
       'skill_assessment_scores.Weights & Biases',
       'skill_assessment_scores.Forecasting',
       'skill_assessment_scores.LangChain', 'skill_assessment_scores.YOLO',
       'skill_assessment_scores.PEFT', 'skill_assessment_scores.Data Science',
       'skill_assessment_scores.MLflow', 'skill_assessment_scores.Pinecone',
       'skill_assessment_scores.Feature Engineering',
       'skill_assessment_scores.BentoML', 'skill_assessment_scores.MLOps',
       'skill_assessment_scores.Qdrant', 'skill_assessment_scores.CNN',
       'skill_assessment_scores.Kubeflow',
       'skill_assessment_scores.Machine Learning',
       'skill_assessment_scores.Reinforcement Learning',
       'skill_assessment_scores.Sentence Transformers',
       'skill_assessment_scores.Haystack',
       'skill_assessment_scores.Hugging Face Transformers',
       'skill_assessment_scores.Semantic Search',
       'skill_assessment_scores.LoRA',
       'skill_assessment_scores.Diffusion Models',
       'skill_assessment_scores.Milvus', 'skill_assessment_scores.Time Series',
       'skill_assessment_scores.Statistical Modeling',
       'skill_assessment_scores.Elasticsearch',
       'skill_assessment_scores.Information Retrieval',
       'skill_assessment_scores.Vector Search',
       'skill_assessment_scores.Learning to Rank',
       'skill_assessment_scores.ASR', 'skill_assessment_scores.TensorFlow',
       'skill_assessment_scores.LLMs',
       'skill_assessment_scores.Computer Vision',
       'skill_assessment_scores.TTS', 'skill_assessment_scores.Weaviate',
       'skill_assessment_scores.RAG', 'skill_assessment_scores.Python',
       'skill_assessment_scores.OpenSearch', 'skill_assessment_scores.BM25',
       'skill_assessment_scores.scikit-learn',
       'skill_assessment_scores.pgvector',
       'skill_assessment_scores.Embeddings',
       'skill_assessment_scores.LlamaIndex', 'skill_assessment_scores.PyTorch',
       'skill_assessment_scores.Deep Learning',
       'skill_assessment_scores.QLoRA'],
      dtype='str')

In [17]:
rows, col = redro_df.shape
for col in redro_df.columns:
    missing_perc = (redro_df[col].isna().sum()/rows)*100
    if missing_perc > 95:
        redro_df.drop(col, axis=1, inplace=True)
        print(f"Removed {col}")

Removed skill_assessment_scores.NLP
Removed skill_assessment_scores.Image Classification
Removed skill_assessment_scores.Fine-tuning LLMs
Removed skill_assessment_scores.Speech Recognition
Removed skill_assessment_scores.GANs
Removed skill_assessment_scores.OpenCV
Removed skill_assessment_scores.Prompt Engineering
Removed skill_assessment_scores.Object Detection
Removed skill_assessment_scores.Recommendation Systems
Removed skill_assessment_scores.FAISS
Removed skill_assessment_scores.Weights & Biases
Removed skill_assessment_scores.Forecasting
Removed skill_assessment_scores.LangChain
Removed skill_assessment_scores.YOLO
Removed skill_assessment_scores.PEFT
Removed skill_assessment_scores.Data Science
Removed skill_assessment_scores.MLflow
Removed skill_assessment_scores.Pinecone
Removed skill_assessment_scores.Feature Engineering
Removed skill_assessment_scores.BentoML
Removed skill_assessment_scores.MLOps
Removed skill_assessment_scores.Qdrant
Removed skill_assessment_scores.CNN
Removed skill_assessment_scores.Kubeflow
Removed skill_assessment_scores.Machine Learning
Removed skill_assessment_scores.Reinforcement Learning
Removed skill_assessment_scores.Sentence Transformers
Removed skill_assessment_scores.Haystack
Removed skill_assessment_scores.Hugging Face Transformers
Removed skill_assessment_scores.Semantic Search
Removed skill_assessment_scores.LoRA
Removed skill_assessment_scores.Diffusion Models
Removed skill_assessment_scores.Milvus
Removed skill_assessment_scores.Time Series
Removed skill_assessment_scores.Statistical Modeling
Removed skill_assessment_scores.Elasticsearch
Removed skill_assessment_scores.Information Retrieval
Removed skill_assessment_scores.Vector Search
Removed skill_assessment_scores.Learning to Rank
Removed skill_assessment_scores.ASR
Removed skill_assessment_scores.TensorFlow
Removed skill_assessment_scores.LLMs
Removed skill_assessment_scores.Computer Vision
Removed skill_assessment_scores.TTS
Removed skill_assessment_scores.Weaviate
Removed skill_assessment_scores.RAG
Removed skill_assessment_scores.Python
Removed skill_assessment_scores.OpenSearch
Removed skill_assessment_scores.BM25
Removed skill_assessment_scores.scikit-learn
Removed skill_assessment_scores.pgvector
Removed skill_assessment_scores.Embeddings
Removed skill_assessment_scores.LlamaIndex
Removed skill_assessment_scores.PyTorch
Removed skill_assessment_scores.Deep Learning
Removed skill_assessment_scores.QLoRA

In [18]:
redro_df.shape

(100000, 23)

In [19]:
redro_df.columns

Index(['profile_completeness_score', 'signup_date', 'last_active_date',
       'open_to_work_flag', 'profile_views_received_30d',
       'applications_submitted_30d', 'recruiter_response_rate',
       'avg_response_time_hours', 'connection_count', 'endorsements_received',
       'notice_period_days', 'preferred_work_mode', 'willing_to_relocate',
       'github_activity_score', 'search_appearance_30d',
       'saved_by_recruiters_30d', 'interview_completion_rate',
       'offer_acceptance_rate', 'verified_email', 'verified_phone',
       'linkedin_connected', 'expected_salary_range_inr_lpa.min',
       'expected_salary_range_inr_lpa.max'],
      dtype='str')

In [20]:
redro_df.dtypes

profile_completeness_score           float64
signup_date                              str
last_active_date                         str
open_to_work_flag                       bool
profile_views_received_30d             int64
applications_submitted_30d             int64
recruiter_response_rate              float64
avg_response_time_hours              float64
connection_count                       int64
endorsements_received                  int64
notice_period_days                     int64
preferred_work_mode                      str
willing_to_relocate                     bool
github_activity_score                float64
search_appearance_30d                  int64
saved_by_recruiters_30d                int64
interview_completion_rate            float64
offer_acceptance_rate                float64
verified_email                          bool
verified_phone                          bool
linkedin_connected                      bool
expected_salary_range_inr_lpa.min    float64
expected_salary_range_inr_lpa.max    float64
dtype: object

In [21]:
redro_df['signup_date'] = pd.to_datetime(redro_df['signup_date'])
redro_df['last_active_date'] = pd.to_datetime(redro_df['last_active_date'])

In [22]:
redro_df.isna().sum()

profile_completeness_score           0
signup_date                          0
last_active_date                     0
open_to_work_flag                    0
profile_views_received_30d           0
applications_submitted_30d           0
recruiter_response_rate              0
avg_response_time_hours              0
connection_count                     0
endorsements_received                0
notice_period_days                   0
preferred_work_mode                  0
willing_to_relocate                  0
github_activity_score                0
search_appearance_30d                0
saved_by_recruiters_30d              0
interview_completion_rate            0
offer_acceptance_rate                0
verified_email                       0
verified_phone                       0
linkedin_connected                   0
expected_salary_range_inr_lpa.min    0
expected_salary_range_inr_lpa.max    0
dtype: int64

In [23]:
redro_df

,profile_completeness_score,signup_date,last_active_date,open_to_work_flag,profile_views_received_30d,applications_submitted_30d,recruiter_response_rate,avg_response_time_hours,connection_count,endorsements_received,...,github_activity_score,search_appearance_30d,saved_by_recruiters_30d,interview_completion_rate,offer_acceptance_rate,verified_email,verified_phone,linkedin_connected,expected_salary_range_inr_lpa.min,expected_salary_range_inr_lpa.max
0,86.9,2025-10-16,2026-05-20,True,23,2,0.34,177.8,356,35,...,9.2,249,4,0.71,0.58,True,True,False,18.7,36.1
1,78.7,2025-07-28,2025-11-12,True,7,1,0.29,171.6,179,3,...,-1.0,107,10,0.62,-1.00,False,False,False,8.8,9.0
2,31.9,2024-08-02,2026-03-21,False,1,9,0.46,119.4,19,46,...,-1.0,28,4,0.86,-1.00,True,False,False,11.2,18.1
3,28.5,2025-07-21,2026-03-25,False,3,9,0.26,104.1,485,22,...,-1.0,5,8,0.35,-1.00,True,True,True,4.6,6.7
4,84.6,2023-10-07,2025-10-01,True,12,2,0.37,116.7,300,14,...,-1.0,67,1,0.74,-1.00,False,True,True,12.4,19.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,41.4,2022-08-11,2025-12-04,False,52,5,0.45,259.8,325,12,...,-1.0,98,7,0.87,-1.00,True,True,False,16.9,26.1
99996,42.7,2025-12-09,2026-03-08,True,42,4,0.41,108.6,292,10,...,44.1,49,0,0.38,-1.00,True,True,False,10.3,6.6
99997,75.9,2025-10-21,2026-03-07,False,84,0,0.33,139.0,442,66,...,10.8,187,26,0.79,0.74,True,False,False,18.3,27.0
99998,49.1,2023-10-14,2025-12-23,True,81,0,0.46,13.7,345,10,...,-1.0,102,3,0.49,0.65,True,False,False,15.0,29.0
99999,80.1,2022-06-28,2025-10-19,False,10,5,0.18,272.0,64,29,...,-1.0,120,7,0.59,-1.00,False,True,True,9.6,18.3

In [24]:
skills_df = df[['candidate_id', 'skills']].explode('skills')
skill_details = pd.json_normalize(skills_df['skills'])

In [25]:
skills_df

       candidate_id                                             skills
0      CAND_0000001  {'name': 'Tailwind', 'proficiency': 'intermedi...
0      CAND_0000001  {'name': 'NLP', 'proficiency': 'advanced', 'en...
0      CAND_0000001  {'name': 'Image Classification', 'proficiency'...
0      CAND_0000001  {'name': 'Fine-tuning LLMs', 'proficiency': 'a...
0      CAND_0000001  {'name': 'Weights & Biases', 'proficiency': 'i...
...             ...                                                ...
99999  CAND_0100000  {'name': 'Photoshop', 'proficiency': 'beginner...
99999  CAND_0100000  {'name': 'Agile', 'proficiency': 'beginner', '...
99999  CAND_0100000  {'name': 'Salesforce CRM', 'proficiency': 'int...
99999  CAND_0100000  {'name': 'Databricks', 'proficiency': 'interme...
99999  CAND_0100000  {'name': 'Java', 'proficiency': 'beginner', 'e...

[960302 rows x 2 columns]

In [26]:
skill_details

                       name   proficiency  endorsements  duration_months
0                  Tailwind  intermediate             3               13
0                       NLP      advanced            37               26
0      Image Classification      advanced             7               40
0          Fine-tuning LLMs      advanced            21               36
0          Weights & Biases  intermediate            13               30
...                     ...           ...           ...              ...
99999             Photoshop      beginner            12               12
99999                 Agile      beginner             5               16
99999        Salesforce CRM  intermediate             9               23
99999            Databricks  intermediate             4               10
99999                  Java      beginner             5                2

[960302 rows x 4 columns]

In [27]:
skills_final = pd.concat(
    [
        skills_df.drop(columns='skills').reset_index(drop=True),
        skill_details.reset_index(drop=True)
    ],
    axis=1
)

In [28]:
skills_final.head(20)

,candidate_id,name,proficiency,endorsements,duration_months
0,CAND_0000001,Tailwind,intermediate,3,13
1,CAND_0000001,NLP,advanced,37,26
2,CAND_0000001,Image Classification,advanced,7,40
3,CAND_0000001,Fine-tuning LLMs,advanced,21,36
4,CAND_0000001,Weights & Biases,intermediate,13,30
5,CAND_0000001,Speech Recognition,advanced,52,33
6,CAND_0000001,Photoshop,intermediate,8,24
7,CAND_0000001,TTS,advanced,56,60
8,CAND_0000001,LoRA,intermediate,0,28
9,CAND_0000001,Apache Beam,intermediate,4,9
10,CAND_0000001,AWS,beginner,5,8
11,CAND_0000001,Flask,beginner,15,15
12,CAND_0000001,BentoML,intermediate,3,36
13,CAND_0000001,Milvus,advanced,40,35
14,CAND_0000001,GANs,advanced,12,19
15,CAND_0000001,Statistical Modeling,intermediate,9,8
16,CAND_0000001,GCP,beginner,7,2
17,CAND_0000002,Project Management,intermediate,14,23
18,CAND_0000002,React,intermediate,6,35
19,CAND_0000002,Photoshop,intermediate,9,35

In [29]:
df.columns

Index(['candidate_id', 'profile', 'career_history', 'education', 'skills',
       'certifications', 'languages', 'redrob_signals'],
      dtype='str')

In [30]:
career = df['career_history']
print(type(career[0]))

<class 'list'>

In [31]:
print(career[0][0])
print(career.loc[0])

{'company': 'Mindtree', 'title': 'Backend Engineer', 'start_date': '2024-03-08', 'end_date': None, 'duration_months': 27, 'is_current': True, 'industry': 'IT Services', 'company_size': '10001+', 'description': 'Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure.'}
[{'company': 'Mindtree', 'title': 'Backend Engineer', 'start_date': '2024-03-08', 'end_date': None, 'duration_months': 27, 'is_current': True, 'industry': 'IT Services', 'company_size': '10001+', 'description': 'Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure.'}, {'company': 'Dunder Mifflin', 'title': 'Analytics Engineer', 'start_date': '2019-07-03', 'end_date': '2024-01-08', 'duration_months': 55, 'is_current': False, 'industry': 'Paper Products', 'company_size': '201-500', 'description': 'Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models.'}]

In [32]:
career

0        [{'company': 'Mindtree', 'title': 'Backend Eng...
1        [{'company': 'Wipro', 'title': 'Operations Man...
2        [{'company': 'TCS', 'title': 'Customer Support...
3        [{'company': 'Dunder Mifflin', 'title': 'Marke...
4        [{'company': 'Stark Industries', 'title': 'Acc...
                               ...
99995    [{'company': 'Wipro', 'title': 'Operations Man...
99996    [{'company': 'Hooli', 'title': 'Mechanical Eng...
99997    [{'company': 'InMobi', 'title': 'Analytics Eng...
99998    [{'company': 'HCL', 'title': '.NET Developer',...
99999    [{'company': 'Acme Corp', 'title': 'Mechanical...
Name: career_history, Length: 100000, dtype: object

In [33]:
career_df = df[['candidate_id', 'career_history']].explode('career_history')
career_df

       candidate_id                                     career_history
0      CAND_0000001  {'company': 'Mindtree', 'title': 'Backend Engi...
0      CAND_0000001  {'company': 'Dunder Mifflin', 'title': 'Analyt...
1      CAND_0000002  {'company': 'Wipro', 'title': 'Operations Mana...
1      CAND_0000002  {'company': 'Wipro', 'title': 'Operations Mana...
1      CAND_0000002  {'company': 'Acme Corp', 'title': 'Marketing M...
...             ...                                                ...
99999  CAND_0100000  {'company': 'Acme Corp', 'title': 'Mechanical ...
99999  CAND_0100000  {'company': 'Stark Industries', 'title': 'Cust...
99999  CAND_0100000  {'company': 'Wayne Enterprises', 'title': 'Cus...
99999  CAND_0100000  {'company': 'Infosys', 'title': 'Accountant', ...
99999  CAND_0100000  {'company': 'Stark Industries', 'title': 'Proj...

[300171 rows x 2 columns]

In [34]:
career_details = pd.json_normalize(career_df['career_history'])
career_details

,company,title,start_date,end_date,duration_months,is_current,industry,company_size,description
0,Mindtree,Backend Engineer,2024-03-08,NaN,27,True,IT Services,10001+,Implemented streaming data pipelines on Kafka ...
0,Dunder Mifflin,Analytics Engineer,2019-07-03,2024-01-08,55,False,Paper Products,201-500,Built and maintained data pipelines on Apache ...
1,Wipro,Operations Manager,2022-11-14,NaN,43,True,IT Services,10001+,Customer support team lead at a SaaS product. ...
1,Wipro,Operations Manager,2021-09-13,2022-11-07,14,False,IT Services,10001+,Mechanical engineering design role at a hardwa...
1,Acme Corp,Marketing Manager,2017-03-08,2021-08-14,54,False,Manufacturing,201-500,Content writing and SEO strategy for a tech-fo...
...,...,...,...,...,...,...,...,...,...
99999,Acme Corp,Mechanical Engineer,2023-09-10,NaN,33,True,Manufacturing,201-500,"Business analyst at a consulting firm, working..."
99999,Stark Industries,Customer Support,2022-03-05,2023-08-27,18,False,Manufacturing,1001-5000,"Business analyst at a consulting firm, working..."
99999,Wayne Enterprises,Customer Support,2018-06-24,2022-02-03,44,False,Conglomerate,10001+,Senior accounting role at a mid-sized company ...
99999,Infosys,Accountant,2015-09-08,2018-06-24,34,False,IT Services,10001+,Operations management role at a logistics comp...
99999,Stark Industries,Project Manager,2014-03-17,2015-09-08,18,False,Manufacturing,1001-5000,Customer support team lead at a SaaS product. ...

In [35]:
profile_df

,candidate_id,anonymized_name,headline,summary,location,country,years_of_experience,current_title,current_company,current_company_size,current_industry
0,CAND_0000001,Ira Vora,"Backend Engineer | SQL, Spark, Cloud",Software / data professional with 6.9 years of...,Toronto,Canada,6.9,Backend Engineer,Mindtree,10001+,IT Services
1,CAND_0000002,Saanvi Sethi,Operations Manager | 12.5+ yrs experience,Professional with 12.5+ years of experience. M...,"Chennai, Tamil Nadu",India,12.5,Operations Manager,Wipro,10001+,IT Services
2,CAND_0000003,Yash Agarwal,Customer Support | 1.1+ yrs experience,Professional with 1.1+ years of experience. I'...,Austin,USA,1.1,Customer Support,TCS,10001+,IT Services
3,CAND_0000004,Anil Bose,Marketing Manager | Driving business outcomes,Professional with 3.8+ years of experience. My...,Sydney,Australia,3.8,Marketing Manager,Dunder Mifflin,201-500,Paper Products
4,CAND_0000005,Aisha Sethi,Accountant | Helping teams scale,Professional with 11.0+ years of experience. I...,"Gurgaon, Haryana",India,11.0,Accountant,Stark Industries,1001-5000,Manufacturing
...,...,...,...,...,...,...,...,...,...,...,...
99995,CAND_0099996,Myra Sethi,Operations Manager | 13.4+ yrs experience,Professional with 13.4+ years of experience. I...,"Ahmedabad, Gujarat",India,13.4,Operations Manager,Wipro,10001+,IT Services
99996,CAND_0099997,Priya Krishnan,Mechanical Engineer | 10.6+ yrs experience,Professional with 10.6+ years of experience. I...,"Bangalore, Karnataka",India,10.6,Mechanical Engineer,Hooli,1001-5000,Software
99997,CAND_0099998,Shreya Agarwal,Analytics Engineer | 7.3+ yrs in data engineering,Software / data professional with 7.3 years of...,"Kochi, Kerala",India,7.3,Analytics Engineer,InMobi,1001-5000,AdTech
99998,CAND_0099999,Diya Menon,.NET Developer | Backend systems & APIs,Software engineer with 4.3 years of experience...,"Bhubaneswar, Odisha",India,4.3,.NET Developer,HCL,10001+,IT Services
99999,CAND_0100000,Reyansh Reddy,Mechanical Engineer | 12.4+ yrs experience,Professional with 12.4+ years of experience. I...,"Kolkata, West Bengal",India,12.4,Mechanical Engineer,Acme Corp,201-500,Manufacturing

In [36]:
career_details.dtypes

company              str
title                str
start_date           str
end_date             str
duration_months    int64
is_current          bool
industry             str
company_size         str
description          str
dtype: object

In [37]:
career_details['start_date'] = pd.to_datetime(career_details['start_date'])
career_details['end_date'] = pd.to_datetime(career_details['end_date'])
career_details.dtypes

company                       str
title                         str
start_date         datetime64[us]
end_date           datetime64[us]
duration_months             int64
is_current                   bool
industry                      str
company_size                  str
description                   str
dtype: object

In [38]:
career_details.info()

<class 'pandas.DataFrame'>
Index: 300171 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   company          300171 non-null  str
 1   title            300171 non-null  str
 2   start_date       300171 non-null  datetime64[us]
 3   end_date         200171 non-null  datetime64[us]
 4   duration_months  300171 non-null  int64
 5   is_current       300171 non-null  bool
 6   industry         300171 non-null  str
 7   company_size     300171 non-null  str
 8   description      300171 non-null  str
dtypes: bool(1), datetime64[us](2), int64(1), str(5)
memory usage: 20.9 MB

In [39]:
career_details.isna().sum()

company                 0
title                   0
start_date              0
end_date           100000
duration_months         0
is_current              0
industry                0
company_size            0
description             0
dtype: int64

In [40]:
career_details.shape

(300171, 9)

In [41]:
career_details['is_current'].value_counts()

is_current
False    200171
True     100000
Name: count, dtype: int64

In [42]:
career_details.duplicated().sum()

np.int64(42455)

In [43]:
career_final = pd.concat(
    [
        career_df.drop(columns='career_history').reset_index(drop=True),
        career_details.reset_index(drop=True)
    ],
    axis=1
)

In [44]:
career_final.duplicated().sum()

np.int64(0)

In [45]:
career_final

,candidate_id,company,title,start_date,end_date,duration_months,is_current,industry,company_size,description
0,CAND_0000001,Mindtree,Backend Engineer,2024-03-08,NaT,27,True,IT Services,10001+,Implemented streaming data pipelines on Kafka ...
1,CAND_0000001,Dunder Mifflin,Analytics Engineer,2019-07-03,2024-01-08,55,False,Paper Products,201-500,Built and maintained data pipelines on Apache ...
2,CAND_0000002,Wipro,Operations Manager,2022-11-14,NaT,43,True,IT Services,10001+,Customer support team lead at a SaaS product. ...
3,CAND_0000002,Wipro,Operations Manager,2021-09-13,2022-11-07,14,False,IT Services,10001+,Mechanical engineering design role at a hardwa...
4,CAND_0000002,Acme Corp,Marketing Manager,2017-03-08,2021-08-14,54,False,Manufacturing,201-500,Content writing and SEO strategy for a tech-fo...
...,...,...,...,...,...,...,...,...,...,...
300166,CAND_0100000,Acme Corp,Mechanical Engineer,2023-09-10,NaT,33,True,Manufacturing,201-500,"Business analyst at a consulting firm, working..."
300167,CAND_0100000,Stark Industries,Customer Support,2022-03-05,2023-08-27,18,False,Manufacturing,1001-5000,"Business analyst at a consulting firm, working..."
300168,CAND_0100000,Wayne Enterprises,Customer Support,2018-06-24,2022-02-03,44,False,Conglomerate,10001+,Senior accounting role at a mid-sized company ...
300169,CAND_0100000,Infosys,Accountant,2015-09-08,2018-06-24,34,False,IT Services,10001+,Operations management role at a logistics comp...
300170,CAND_0100000,Stark Industries,Project Manager,2014-03-17,2015-09-08,18,False,Manufacturing,1001-5000,Customer support team lead at a SaaS product. ...

In [46]:
(career_final.isna().sum()/len(career_final))*100

candidate_id        0.000000
company             0.000000
title               0.000000
start_date          0.000000
end_date           33.314344
duration_months     0.000000
is_current          0.000000
industry            0.000000
company_size        0.000000
description         0.000000
dtype: float64

In [47]:
career_details.shape

(300171, 9)

In [48]:
df.columns

Index(['candidate_id', 'profile', 'career_history', 'education', 'skills',
       'certifications', 'languages', 'redrob_signals'],
      dtype='str')

In [49]:
education = df['education']
education

0        [{'institution': 'Lovely Professional Universi...
1        [{'institution': 'Local Engineering College', ...
2        [{'institution': 'Local Engineering College', ...
3        [{'institution': 'Local Engineering College', ...
4        [{'institution': 'Chandigarh University', 'deg...
                               ...
99995    [{'institution': 'KIIT University', 'degree': ...
99996    [{'institution': 'SRM Chennai', 'degree': 'Ph....
99997    [{'institution': 'Manipal Institute of Technol...
99998    [{'institution': 'RV College of Engineering', ...
99999    [{'institution': 'Chandigarh University', 'deg...
Name: education, Length: 100000, dtype: object

In [50]:
education_details = df[['candidate_id', 'education']].explode('education')
education_details

       candidate_id                                          education
0      CAND_0000001  {'institution': 'Lovely Professional Universit...
1      CAND_0000002  {'institution': 'Local Engineering College', '...
2      CAND_0000003  {'institution': 'Local Engineering College', '...
2      CAND_0000003  {'institution': 'Chandigarh University', 'degr...
3      CAND_0000004  {'institution': 'Local Engineering College', '...
...             ...                                                ...
99997  CAND_0099998  {'institution': 'Manipal Institute of Technolo...
99997  CAND_0099998  {'institution': 'Lovely Professional Universit...
99998  CAND_0099999  {'institution': 'RV College of Engineering', '...
99999  CAND_0100000  {'institution': 'Chandigarh University', 'degr...
99999  CAND_0100000  {'institution': 'Christ University', 'degree':...

[139778 rows x 2 columns]

In [51]:
education_normalize = pd.json_normalize(education_details['education'])
education_normalize

,institution,degree,field_of_study,start_year,end_year,grade,tier
0,Lovely Professional University,B.E.,Computer Science,2017,2020,8.24 CGPA,tier_3
1,Local Engineering College,B.Sc,Mathematics,2007,2011,77%,tier_4
2,Local Engineering College,M.E.,Chemical Engineering,2005,2010,6.82 CGPA,tier_4
2,Chandigarh University,M.Sc,Information Technology,2017,2021,87%,tier_3
3,Local Engineering College,B.Tech,Machine Learning,2015,2019,7.72 CGPA,tier_4
...,...,...,...,...,...,...,...
99997,Manipal Institute of Technology,M.S.,Artificial Intelligence,2004,2008,65%,tier_2
99997,Lovely Professional University,B.E.,Machine Learning,2007,2011,6.56 CGPA,tier_3
99998,RV College of Engineering,M.Sc,Commerce,2007,2011,8.92 CGPA,tier_2
99999,Chandigarh University,B.Sc,Computer Science,2008,2012,6.50 CGPA,tier_3
99999,Christ University,Ph.D,Data Science,2001,2006,9.06 CGPA,tier_3

In [52]:
(education_normalize.isna().sum()/len(education_normalize))*100

institution       0.0
degree            0.0
field_of_study    0.0
start_year        0.0
end_year          0.0
grade             0.0
tier              0.0
dtype: float64

In [53]:
education_final = pd.concat(
    [
        education_details.drop(columns='education').reset_index(drop=True),
        education_normalize.reset_index(drop=True)
    ],
    axis=1
)

In [54]:
education_final

,candidate_id,institution,degree,field_of_study,start_year,end_year,grade,tier
0,CAND_0000001,Lovely Professional University,B.E.,Computer Science,2017,2020,8.24 CGPA,tier_3
1,CAND_0000002,Local Engineering College,B.Sc,Mathematics,2007,2011,77%,tier_4
2,CAND_0000003,Local Engineering College,M.E.,Chemical Engineering,2005,2010,6.82 CGPA,tier_4
3,CAND_0000003,Chandigarh University,M.Sc,Information Technology,2017,2021,87%,tier_3
4,CAND_0000004,Local Engineering College,B.Tech,Machine Learning,2015,2019,7.72 CGPA,tier_4
...,...,...,...,...,...,...,...,...
139773,CAND_0099998,Manipal Institute of Technology,M.S.,Artificial Intelligence,2004,2008,65%,tier_2
139774,CAND_0099998,Lovely Professional University,B.E.,Machine Learning,2007,2011,6.56 CGPA,tier_3
139775,CAND_0099999,RV College of Engineering,M.Sc,Commerce,2007,2011,8.92 CGPA,tier_2
139776,CAND_0100000,Chandigarh University,B.Sc,Computer Science,2008,2012,6.50 CGPA,tier_3
139777,CAND_0100000,Christ University,Ph.D,Data Science,2001,2006,9.06 CGPA,tier_3

In [55]:
df.columns

Index(['candidate_id', 'profile', 'career_history', 'education', 'skills',
       'certifications', 'languages', 'redrob_signals'],
      dtype='str')

In [56]:
certifications = df['certifications']
certifications

0                                                       []
1                                                       []
2                                                       []
3        [{'name': 'AWS Certified Cloud Practitioner', ...
4                                                       []
                               ...
99995                                                   []
99996                                                   []
99997    [{'name': 'AWS Certified Cloud Practitioner', ...
99998                                                   []
99999                                                   []
Name: certifications, Length: 100000, dtype: object

In [57]:
print(certifications.isna().sum())

0

In [58]:
certifications = df[['candidate_id', 'certifications']].explode('certifications')
certifications

       candidate_id                                     certifications
0      CAND_0000001                                                NaN
1      CAND_0000002                                                NaN
2      CAND_0000003                                                NaN
3      CAND_0000004  {'name': 'AWS Certified Cloud Practitioner', '...
3      CAND_0000004  {'name': 'Scrum Master Certified', 'issuer': '...
...             ...                                                ...
99995  CAND_0099996                                                NaN
99996  CAND_0099997                                                NaN
99997  CAND_0099998  {'name': 'AWS Certified Cloud Practitioner', '...
99998  CAND_0099999                                                NaN
99999  CAND_0100000                                                NaN

[112503 rows x 2 columns]

In [59]:
certifications['certifications'].isna().sum()

np.int64(75019)

In [60]:
certifications_details = pd.json_normalize(certifications['certifications'])
certifications_details

                                   name          issuer    year
0                                   NaN             NaN     NaN
1                                   NaN             NaN     NaN
2                                   NaN             NaN     NaN
3      AWS Certified Cloud Practitioner             AWS  2025.0
3                Scrum Master Certified  Scrum Alliance  2025.0
...                                 ...             ...     ...
99995                               NaN             NaN     NaN
99996                               NaN             NaN     NaN
99997  AWS Certified Cloud Practitioner             AWS  2025.0
99998                               NaN             NaN     NaN
99999                               NaN             NaN     NaN

[112503 rows x 3 columns]

In [61]:
certifications_details.dtypes

name          str
issuer        str
year      float64
dtype: object

In [62]:
certifications_final = pd.concat(
    [
        certifications.drop(columns='certifications').reset_index(drop=True),
        certifications_details.reset_index(drop=True)
    ],
    axis=1
)
certifications_final

        candidate_id                              name          issuer    year
0       CAND_0000001                               NaN             NaN     NaN
1       CAND_0000002                               NaN             NaN     NaN
2       CAND_0000003                               NaN             NaN     NaN
3       CAND_0000004  AWS Certified Cloud Practitioner             AWS  2025.0
4       CAND_0000004            Scrum Master Certified  Scrum Alliance  2025.0
...              ...                               ...             ...     ...
112498  CAND_0099996                               NaN             NaN     NaN
112499  CAND_0099997                               NaN             NaN     NaN
112500  CAND_0099998  AWS Certified Cloud Practitioner             AWS  2025.0
112501  CAND_0099999                               NaN             NaN     NaN
112502  CAND_0100000                               NaN             NaN     NaN

[112503 rows x 4 columns]

In [63]:
certifications_final['year'] = certifications_final['year'].astype('Int64')
certifications_final

        candidate_id                              name          issuer  year
0       CAND_0000001                               NaN             NaN  <NA>
1       CAND_0000002                               NaN             NaN  <NA>
2       CAND_0000003                               NaN             NaN  <NA>
3       CAND_0000004  AWS Certified Cloud Practitioner             AWS  2025
4       CAND_0000004            Scrum Master Certified  Scrum Alliance  2025
...              ...                               ...             ...   ...
112498  CAND_0099996                               NaN             NaN  <NA>
112499  CAND_0099997                               NaN             NaN  <NA>
112500  CAND_0099998  AWS Certified Cloud Practitioner             AWS  2025
112501  CAND_0099999                               NaN             NaN  <NA>
112502  CAND_0100000                               NaN             NaN  <NA>

[112503 rows x 4 columns]

In [64]:
certifications_final.isna().sum()

candidate_id        0
name            75019
issuer          75019
year            75019
dtype: int64

In [65]:
certifications_final.shape

(112503, 4)

In [66]:
df.columns

Index(['candidate_id', 'profile', 'career_history', 'education', 'skills',
       'certifications', 'languages', 'redrob_signals'],
      dtype='str')

In [67]:
languages = df['languages']
languages

0        [{'language': 'English', 'proficiency': 'profe...
1        [{'language': 'English', 'proficiency': 'profe...
2        [{'language': 'English', 'proficiency': 'profe...
3        [{'language': 'English', 'proficiency': 'profe...
4        [{'language': 'English', 'proficiency': 'profe...
                               ...
99995    [{'language': 'English', 'proficiency': 'profe...
99996    [{'language': 'English', 'proficiency': 'nativ...
99997    [{'language': 'English', 'proficiency': 'profe...
99998    [{'language': 'English', 'proficiency': 'profe...
99999    [{'language': 'English', 'proficiency': 'profe...
Name: languages, Length: 100000, dtype: object

In [68]:
languages.loc[0]

[{'language': 'English', 'proficiency': 'professional'},
 {'language': 'Hindi', 'proficiency': 'conversational'}]

In [69]:
languages = df[['candidate_id', 'languages']].explode('languages')
languages

       candidate_id                                          languages
0      CAND_0000001  {'language': 'English', 'proficiency': 'profes...
0      CAND_0000001  {'language': 'Hindi', 'proficiency': 'conversa...
1      CAND_0000002  {'language': 'English', 'proficiency': 'profes...
1      CAND_0000002  {'language': 'Hindi', 'proficiency': 'conversa...
2      CAND_0000003  {'language': 'English', 'proficiency': 'profes...
...             ...                                                ...
99997  CAND_0099998  {'language': 'Hindi', 'proficiency': 'conversa...
99998  CAND_0099999  {'language': 'English', 'proficiency': 'profes...
99998  CAND_0099999     {'language': 'Hindi', 'proficiency': 'native'}
99999  CAND_0100000  {'language': 'English', 'proficiency': 'profes...
99999  CAND_0100000  {'language': 'Hindi', 'proficiency': 'conversa...

[200000 rows x 2 columns]

In [70]:
language_df = pd.json_normalize(languages['languages'])
language_df

      language     proficiency
0      English    professional
0        Hindi  conversational
1      English    professional
1        Hindi  conversational
2      English    professional
...        ...             ...
99997    Hindi  conversational
99998  English    professional
99998    Hindi          native
99999  English    professional
99999    Hindi  conversational

[200000 rows x 2 columns]

In [71]:
language_df.dtypes

language       str
proficiency    str
dtype: object

In [72]:
language_df.isna().sum()

language       0
proficiency    0
dtype: int64

In [73]:
languages_final = pd.concat(
    [
        languages.drop(columns='languages').reset_index(drop=True),
        language_df.reset_index(drop=True)
    ],
    axis=1
)
languages_final

        candidate_id language     proficiency
0       CAND_0000001  English    professional
1       CAND_0000001    Hindi  conversational
2       CAND_0000002  English    professional
3       CAND_0000002    Hindi  conversational
4       CAND_0000003  English    professional
...              ...      ...             ...
199995  CAND_0099998    Hindi  conversational
199996  CAND_0099999  English    professional
199997  CAND_0099999    Hindi          native
199998  CAND_0100000  English    professional
199999  CAND_0100000    Hindi  conversational

[200000 rows x 3 columns]

In [74]:
profile_df

,candidate_id,anonymized_name,headline,summary,location,country,years_of_experience,current_title,current_company,current_company_size,current_industry
0,CAND_0000001,Ira Vora,"Backend Engineer | SQL, Spark, Cloud",Software / data professional with 6.9 years of...,Toronto,Canada,6.9,Backend Engineer,Mindtree,10001+,IT Services
1,CAND_0000002,Saanvi Sethi,Operations Manager | 12.5+ yrs experience,Professional with 12.5+ years of experience. M...,"Chennai, Tamil Nadu",India,12.5,Operations Manager,Wipro,10001+,IT Services
2,CAND_0000003,Yash Agarwal,Customer Support | 1.1+ yrs experience,Professional with 1.1+ years of experience. I'...,Austin,USA,1.1,Customer Support,TCS,10001+,IT Services
3,CAND_0000004,Anil Bose,Marketing Manager | Driving business outcomes,Professional with 3.8+ years of experience. My...,Sydney,Australia,3.8,Marketing Manager,Dunder Mifflin,201-500,Paper Products
4,CAND_0000005,Aisha Sethi,Accountant | Helping teams scale,Professional with 11.0+ years of experience. I...,"Gurgaon, Haryana",India,11.0,Accountant,Stark Industries,1001-5000,Manufacturing
...,...,...,...,...,...,...,...,...,...,...,...
99995,CAND_0099996,Myra Sethi,Operations Manager | 13.4+ yrs experience,Professional with 13.4+ years of experience. I...,"Ahmedabad, Gujarat",India,13.4,Operations Manager,Wipro,10001+,IT Services
99996,CAND_0099997,Priya Krishnan,Mechanical Engineer | 10.6+ yrs experience,Professional with 10.6+ years of experience. I...,"Bangalore, Karnataka",India,10.6,Mechanical Engineer,Hooli,1001-5000,Software
99997,CAND_0099998,Shreya Agarwal,Analytics Engineer | 7.3+ yrs in data engineering,Software / data professional with 7.3 years of...,"Kochi, Kerala",India,7.3,Analytics Engineer,InMobi,1001-5000,AdTech
99998,CAND_0099999,Diya Menon,.NET Developer | Backend systems & APIs,Software engineer with 4.3 years of experience...,"Bhubaneswar, Odisha",India,4.3,.NET Developer,HCL,10001+,IT Services
99999,CAND_0100000,Reyansh Reddy,Mechanical Engineer | 12.4+ yrs experience,Professional with 12.4+ years of experience. I...,"Kolkata, West Bengal",India,12.4,Mechanical Engineer,Acme Corp,201-500,Manufacturing

In [75]:
career_final

,candidate_id,company,title,start_date,end_date,duration_months,is_current,industry,company_size,description
0,CAND_0000001,Mindtree,Backend Engineer,2024-03-08,NaT,27,True,IT Services,10001+,Implemented streaming data pipelines on Kafka ...
1,CAND_0000001,Dunder Mifflin,Analytics Engineer,2019-07-03,2024-01-08,55,False,Paper Products,201-500,Built and maintained data pipelines on Apache ...
2,CAND_0000002,Wipro,Operations Manager,2022-11-14,NaT,43,True,IT Services,10001+,Customer support team lead at a SaaS product. ...
3,CAND_0000002,Wipro,Operations Manager,2021-09-13,2022-11-07,14,False,IT Services,10001+,Mechanical engineering design role at a hardwa...
4,CAND_0000002,Acme Corp,Marketing Manager,2017-03-08,2021-08-14,54,False,Manufacturing,201-500,Content writing and SEO strategy for a tech-fo...
...,...,...,...,...,...,...,...,...,...,...
300166,CAND_0100000,Acme Corp,Mechanical Engineer,2023-09-10,NaT,33,True,Manufacturing,201-500,"Business analyst at a consulting firm, working..."
300167,CAND_0100000,Stark Industries,Customer Support,2022-03-05,2023-08-27,18,False,Manufacturing,1001-5000,"Business analyst at a consulting firm, working..."
300168,CAND_0100000,Wayne Enterprises,Customer Support,2018-06-24,2022-02-03,44,False,Conglomerate,10001+,Senior accounting role at a mid-sized company ...
300169,CAND_0100000,Infosys,Accountant,2015-09-08,2018-06-24,34,False,IT Services,10001+,Operations management role at a logistics comp...
300170,CAND_0100000,Stark Industries,Project Manager,2014-03-17,2015-09-08,18,False,Manufacturing,1001-5000,Customer support team lead at a SaaS product. ...

In [76]:
profile_df.shape

(100000, 11)

In [77]:
redro_df.shape

(100000, 23)

In [78]:
education_final

,candidate_id,institution,degree,field_of_study,start_year,end_year,grade,tier
0,CAND_0000001,Lovely Professional University,B.E.,Computer Science,2017,2020,8.24 CGPA,tier_3
1,CAND_0000002,Local Engineering College,B.Sc,Mathematics,2007,2011,77%,tier_4
2,CAND_0000003,Local Engineering College,M.E.,Chemical Engineering,2005,2010,6.82 CGPA,tier_4
3,CAND_0000003,Chandigarh University,M.Sc,Information Technology,2017,2021,87%,tier_3
4,CAND_0000004,Local Engineering College,B.Tech,Machine Learning,2015,2019,7.72 CGPA,tier_4
...,...,...,...,...,...,...,...,...
139773,CAND_0099998,Manipal Institute of Technology,M.S.,Artificial Intelligence,2004,2008,65%,tier_2
139774,CAND_0099998,Lovely Professional University,B.E.,Machine Learning,2007,2011,6.56 CGPA,tier_3
139775,CAND_0099999,RV College of Engineering,M.Sc,Commerce,2007,2011,8.92 CGPA,tier_2
139776,CAND_0100000,Chandigarh University,B.Sc,Computer Science,2008,2012,6.50 CGPA,tier_3
139777,CAND_0100000,Christ University,Ph.D,Data Science,2001,2006,9.06 CGPA,tier_3

In [79]:
education_final

,candidate_id,institution,degree,field_of_study,start_year,end_year,grade,tier
0,CAND_0000001,Lovely Professional University,B.E.,Computer Science,2017,2020,8.24 CGPA,tier_3
1,CAND_0000002,Local Engineering College,B.Sc,Mathematics,2007,2011,77%,tier_4
2,CAND_0000003,Local Engineering College,M.E.,Chemical Engineering,2005,2010,6.82 CGPA,tier_4
3,CAND_0000003,Chandigarh University,M.Sc,Information Technology,2017,2021,87%,tier_3
4,CAND_0000004,Local Engineering College,B.Tech,Machine Learning,2015,2019,7.72 CGPA,tier_4
...,...,...,...,...,...,...,...,...
139773,CAND_0099998,Manipal Institute of Technology,M.S.,Artificial Intelligence,2004,2008,65%,tier_2
139774,CAND_0099998,Lovely Professional University,B.E.,Machine Learning,2007,2011,6.56 CGPA,tier_3
139775,CAND_0099999,RV College of Engineering,M.Sc,Commerce,2007,2011,8.92 CGPA,tier_2
139776,CAND_0100000,Chandigarh University,B.Sc,Computer Science,2008,2012,6.50 CGPA,tier_3
139777,CAND_0100000,Christ University,Ph.D,Data Science,2001,2006,9.06 CGPA,tier_3

In [80]:
df.columns

Index(['candidate_id', 'profile', 'career_history', 'education', 'skills',
       'certifications', 'languages', 'redrob_signals'],
      dtype='str')

In [81]:
skills_final

,candidate_id,name,proficiency,endorsements,duration_months
0,CAND_0000001,Tailwind,intermediate,3,13
1,CAND_0000001,NLP,advanced,37,26
2,CAND_0000001,Image Classification,advanced,7,40
3,CAND_0000001,Fine-tuning LLMs,advanced,21,36
4,CAND_0000001,Weights & Biases,intermediate,13,30
...,...,...,...,...,...
960297,CAND_0100000,Photoshop,beginner,12,12
960298,CAND_0100000,Agile,beginner,5,16
960299,CAND_0100000,Salesforce CRM,intermediate,9,23
960300,CAND_0100000,Databricks,intermediate,4,10
960301,CAND_0100000,Java,beginner,5,2

In [82]:
skills_final.to_csv('skills.csv', index=False)

career_final.to_csv('career_history.csv', index=False)

education_final.to_csv('education.csv', index=False)

certifications_final.to_csv('certifications.csv', index=False)

languages_final.to_csv('languages.csv', index=False)

In [84]:
profile_df.to_csv('profile.csv', index=False)